import moment from 'moment-timezone';

export default {
  name: 'Satellites',
  icon: 'rocket',
  path: '/satellite/:id',
  component: 'Dashboard',
  props: {
    socketType: 'live',
    defaultLayout: {
      lg: [
        {
          i: 'satellite-default-a',
          x: 0,
          y: 0,
          w: 4,
          h: 7,
          component: {
            name: 'Status',
          },
        },
        {
          i: 'satellite-default-b',
          x: 4,
          y: 0,
          w: 4,
          h: 7,
          component: {
            name: 'DisplayValue',
            props: {
              name: 'beagle1 CPU',
              displayValues: [
                {
                  name: 'CPU Load',
                  nodeProcess: 'beagle1:cpu',
                  dataKey: 'device_cpu_load_000',
                  unit: '%',
                  processDataKey: (x) => x.toFixed(2),
                },
                {
                  name: 'GiB',
                  nodeProcess: 'beagle1:cpu',
                  dataKey: 'device_cpu_gib_000',
                  unit: 'GiB',
                  processDataKey: (x) => x.toFixed(2),
                },
                {
                  name: 'Max GiB',
                  nodeProcess: 'beagle1:cpu',
                  dataKey: 'device_cpu_maxgib_000',
                  unit: 'GiB',
                  processDataKey: (x) => x.toFixed(2),
                },
              ],
            },
          },
        },
        {
          i: 'satellite-default-c',
          x: 8,
          y: 0,
          w: 4,
          h: 7,
          component: {
            name: 'Clock',
          },
        },
        {
          i: 'satellite-default-d',
          x: 0,
          y: 1,
          w: 12,
          h: 10,
          component: {
            name: 'Commands',
          },
        },
        {
          i: 'satellite-default-e',
          x: 0,
          y: 2,
          w: 6,
          h: 21,
          component: {
            name: 'Globe',
            props: {
              name: 'Orbit',
              orbits: [
                {
                  name: 'neutron1',
                  modelFileName: 'cubesat1.glb',
                  nodeProcess: 'cubesat1:propagator_simple',
                  dataKey: 'node_loc_pos_eci',
                  live: true,
                  position: [21.289373, 157.917480, 350000.0],
                  orientation: {
                    d: {
                      x: 0,
                      y: 0,
                      z: 0,
                    },
                    w: 0,
                  },
                },
              ],
              overlays: [
                {
                  markerColor: 'RED',
                  geoJson: {
                    type: 'Polygon',
                    coordinates: [
                      [[30, 10], [40, 40], [20, 40], [10, 20], [30, 10]],
                    ],
                  },
                },
              ],
            },
          },
        },
        {
          i: 'satellite-default-f',
          x: 6,
          y: 2,
          w: 6,
          h: 21,
          component: {
            name: 'Attitude',
            props: {
              attitudes: [
                {
                  name: 'n1',
                  nodeProcess: 'cubesat1:propagator_simple',
                  dataKey: 'node_loc_att_icrf',
                  quaternions: {
                    d: {
                      x: 0,
                      y: 0,
                      z: 0,
                    },
                    w: 0,
                  },
                  live: true,
                },
              ],
            },
          },
        },
        {
          i: 'satellite-default-g',
          x: 0,
          y: 3,
          w: 12,
          h: 18,
          component: {
            name: 'Chart',
            props: {
              name: 'CPU',
              XDataKey: 'node_utc',
              processXDataKey: (x) => moment.unix((((x + 2400000.5) - 2440587.5) * 86400.0)).format('YYYY-MM-DDTHH:mm:ss'),
              plots: [
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  marker: {
                    color: 'red',
                  },
                  name: '1',
                  YDataKey: 'device_cpu_load_000',
                  processYDataKey: (x) => x,
                  nodeProcess: 'beagle1:cpu',
                  live: true,
                },
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  marker: {
                    color: 'blue',
                  },
                  name: '2',
                  YDataKey: 'device_cpu_gib_000',
                  processYDataKey: (x) => x,
                  nodeProcess: 'beagle1:cpu',
                  live: true,
                },
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  marker: {
                    color: 'orange',
                  },
                  name: '3',
                  YDataKey: 'device_cpu_maxgib_000',
                  processYDataKey: (x) => x,
                  nodeProcess: 'beagle1:cpu',
                  live: true,
                },
              ],
            },
          },
        },
        {
          i: 'satellite-default-h',
          x: 0,
          y: 4,
          w: 12,
          h: 18,
          component: {
            name: 'Chart',
            props: {
              name: 'EPS Buses',
              XDataKey: 'node_utc',
              processXDataKey: (x) => moment.unix((((x + 2400000.5) - 2440587.5) * 86400.0)).format('YYYY-MM-DDTHH:mm:ss'),
              plots: [
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  marker: {
                    color: 'blue',
                  },
                  name: '3.3V Voltage',
                  YDataKey: 'device_bus_volt_002',
                  nodeProcess: 'beagle1:eps',
                  live: true,
                },
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  marker: {
                    color: 'red',
                  },
                  name: '5V Voltage',
                  YDataKey: 'device_bus_volt_001',
                  nodeProcess: 'beagle1:eps',
                  live: true,
                },
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  marker: {
                    color: 'orange',
                  },
                  name: '12V Voltage',
                  YDataKey: 'device_bus_volt_003',
                  nodeProcess: 'beagle1:eps',
                  live: true,
                },
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  marker: {
                    color: 'red',
                  },
                  name: '5V Amperage',
                  YDataKey: 'device_bus_amp_001',
                  nodeProcess: 'beagle1:eps',
                  live: true,
                },
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  marker: {
                    color: 'blue',
                  },
                  name: '3.3V Amperage',
                  YDataKey: 'device_bus_amp_002',
                  nodeProcess: 'beagle1:eps',
                  live: true,
                },
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  marker: {
                    color: 'orange',
                  },
                  name: '12V Amperage',
                  YDataKey: 'device_bus_amp_003',
                  nodeProcess: 'beagle1:eps',
                  live: true,
                },
              ],
            },
          },
        },
        {
          i: 'satellite-default-i',
          x: 0,
          y: 5,
          w: 12,
          h: 18,
          component: {
            name: 'Chart',
            props: {
              name: 'EPS Battery Charge Regulators',
              XDataKey: 'node_utc',
              processXDataKey: (x) => moment.unix((((x + 2400000.5) - 2440587.5) * 86400.0)).format('YYYY-MM-DDTHH:mm:ss'),
              plots: [
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  marker: {
                    color: 'blue',
                  },
                  name: 'Amp 000',
                  YDataKey: 'device_bcreg_amp_000',
                  nodeProcess: 'beagle1:eps',
                  live: true,
                },
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  marker: {
                    color: 'red',
                  },
                  name: 'Volt 000',
                  YDataKey: 'device_bcreg_volt_000',
                  nodeProcess: 'beagle1:eps',
                  live: true,
                },
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  marker: {
                    color: 'blue',
                  },
                  name: 'Amp 001',
                  YDataKey: 'device_bcreg_amp_001',
                  nodeProcess: 'beagle1:eps',
                  live: true,
                },
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  marker: {
                    color: 'red',
                  },
                  name: 'Volt 001',
                  YDataKey: 'device_bcreg_volt_001',
                  nodeProcess: 'beagle1:eps',
                  live: true,
                },
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  marker: {
                    color: 'blue',
                  },
                  name: 'Amp 002',
                  YDataKey: 'device_bcreg_amp_002',
                  nodeProcess: 'beagle1:eps',
                  live: true,
                },
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  marker: {
                    color: 'red',
                  },
                  name: 'Volt 002',
                  YDataKey: 'device_bcreg_volt_002',
                  nodeProcess: 'beagle1:eps',
                  live: true,
                },
              ],
            },
          },
        },
        {
          i: 'satellite-default-j',
          x: 0,
          y: 6,
          w: 12,
          h: 18,
          component: {
            name: 'Chart',
            props: {
              name: 'EPS Battery',
              plots: [
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  marker: {
                    color: 'red',
                  },
                  name: 'Amerage',
                  YDataKey: 'device_batt_amp_000',
                  nodeProcess: 'beagle1:eps',
                  live: true,
                },
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  mode: 'marker',
                  marker: {
                    color: 'blue',
                  },
                  name: 'Voltage',
                  YDataKey: 'device_batt_volt_000',
                  nodeProcess: 'beagle1:eps',
                  live: true,
                },
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  mode: 'marker',
                  marker: {
                    color: 'blue',
                  },
                  name: 'Power',
                  YDataKey: 'device_batt_power_000',
                  nodeProcess: 'beagle1:eps',
                  live: true,
                },
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  marker: {
                    color: 'red',
                  },
                  name: 'Charge',
                  YDataKey: 'device_batt_charge_000',
                  nodeProcess: 'beagle1:eps',
                  live: true,
                },
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  marker: {
                    color: 'red',
                  },
                  name: 'Battery Percentage',
                  YDataKey: 'device_batt_percentage_000',
                  nodeProcess: 'beagle1:eps',
                  live: true,
                },
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  marker: {
                    color: 'red',
                  },
                  name: 'Battery Time Remaining',
                  YDataKey: 'device_batt_time_remaining_000',
                  nodeProcess: 'beagle1:eps',
                  live: true,
                },
              ],
            },
          },
        },
      ],
    },
  },
  children: [
    {
      name: 'neutron1',
      path: '/neutron1',
      icon: 'qrcode',
      defaultLayout: {
        lg: [
          {
            i: 'satellite-neutron1-a',
            x: 0,
            y: 0,
            w: 3,
            h: 7,
            component: {
              name: 'Status',
            },
          },
          {
            i: 'satellite-neutron1-ba',
            x: 3,
            y: 0,
            w: 3,
            h: 7,
            component: {
              name: 'DisplayValue',
              props: {
                name: 'beagle1 EPS',
                displayValues: [
                  {
                    name: 'Battery Capacity',
                    nodeProcess: 'neutron1:soh',
                    dataKey: 'node_battcap',
                    unit: 'Whr',
                    processDataKey: (x) => x.toFixed(2),
                  },
                  {
                    name: 'Battery Percent',
                    nodeProcess: 'neutron1:soh',
                    dataKey: 'device_batt_percentage_000',
                    unit: '%',
                    processDataKey: (x) => x.toFixed(2),
                  },
                  {
                    name: 'Power Gen',
                    nodeProcess: 'neutron1:soh',
                    dataKey: 'node_powgen',
                    unit: 'W',
                    processDataKey: (x) => x.toFixed(2),
                  },
                  {
                    name: 'Power Use',
                    nodeProcess: 'neutron1:soh',
                    dataKey: 'node_powuse',
                    unit: 'W',
                    processDataKey: (x) => x.toFixed(2),
                  },
                ],
              },
            },
          },
          {
            i: 'satellite-neutron1-b',
            x: 6,
            y: 0,
            w: 3,
            h: 7,
            component: {
              name: 'DisplayValue',
              props: {
                name: 'beagle1 CPU',
                displayValues: [
                  {
                    name: 'CPU Load',
                    nodeProcess: 'neutron1:soh',
                    dataKey: 'device_cpu_load_000',
                    unit: '',
                    processDataKey: (x) => x.toFixed(2),
                  },
                  {
                    name: 'CPU Utilization',
                    nodeProcess: 'neutron1:soh',
                    dataKey: 'cpu_utilization_000',
                    unit: '',
                    processDataKey: (x) => x.toFixed(2),
                  },
                  {
                    name: 'Max GiB',
                    nodeProcess: 'neutron1:soh',
                    dataKey: 'device_cpu_maxgib_000',
                    unit: 'GiB',
                    processDataKey: (x) => x.toFixed(2),
                  },
                  {
                    name: 'GiB',
                    nodeProcess: 'neutron1:soh',
                    dataKey: 'device_cpu_gib_000',
                    unit: 'GiB',
                    processDataKey: (x) => x.toFixed(2),
                  },
                ],
              },
            },
          },
          {
            i: 'satellite-neutron1-c',
            x: 9,
            y: 0,
            w: 3,
            h: 7,
            component: {
              name: 'Replacement',
            },
          },
          {
            i: 'satellite-neutron1-d',
            x: 0,
            y: 1,
            w: 12,
            h: 10,
            component: {
              name: 'Commands',
            },
          },
          {
            i: 'satellite-neutron1-e',
            x: 0,
            y: 2,
            w: 6,
            h: 21,
            component: {
              name: 'Globe',
              props: {
                name: 'Orbit',
                orbits: [
                  {
                    name: 'neutron1',
                    modelFileName: 'cubesat1.glb',
                    nodeProcess: 'cubesat1:propagator_simple',
                    dataKey: 'node_loc_pos_eci',
                    live: true,
                    position: [21.289373, 157.917480, 350000.0],
                    orientation: {
                      d: {
                        x: 0,
                        y: 0,
                        z: 0,
                      },
                      w: 0,
                    },
                  },
                ],
                overlays: [
                  {
                    color: 'CRIMSON',
                    geoJson: {
                      type: 'Polygon',
                      coordinates: [
                        [[30, 10], [40, 40], [20, 40], [10, 20], [30, 10]],
                      ],
                    },
                  },
                ],
              },
            },
          },
          {
            i: 'satellite-neutron1-f',
            x: 6,
            y: 2,
            w: 6,
            h: 21,
            component: {
              name: 'Attitude',
              props: {
                name: 'Attitude',
                attitudes: [
                  {
                    name: 'n1',
                    nodeProcess: 'cubesat1:propagator_simple',
                    dataKey: 'node_loc_att_icrf',
                    quaternions: {
                      d: {
                        x: 0,
                        y: 0,
                        z: 0,
                      },
                      w: 0,
                    },
                    live: true,
                  },
                ],
              },
            },
          },
          {
            i: 'satellite-neutron1-g',
            x: 0,
            y: 3,
            w: 12,
            h: 18,
            component: {
              name: 'Chart',
              props: {
                name: 'CPU',
                XDataKey: 'node_utc',
                processXDataKey: (x) => moment.unix((((x + 2400000.5) - 2440587.5) * 86400.0)).format('YYYY-MM-DDTHH:mm:ss'),
                plots: [
                  {
                    x: [],
                    y: [],
                    type: 'scatter',
                    marker: {
                      color: 'red',
                    },
                    name: 'Load',
                    YDataKey: 'device_cpu_load_000',
                    processYDataKey: (x) => x,
                    nodeProcess: 'neutron1:soh',
                    live: true,
                  },
                  {
                    x: [],
                    y: [],
                    type: 'scatter',
                    marker: {
                      color: 'blue',
                    },
                    name: 'Utilization',
                    YDataKey: 'cpu_utilization_000',
                    processYDataKey: (x) => x,
                    nodeProcess: 'neutron1:soh',
                    live: true,
                  },
                ],
              },
            },
          },
          {
            i: 'satellite-neutron1-hc',
            x: 0,
            y: 4,
            w: 12,
            h: 18,
            component: {
              name: 'Chart',
              props: {
                name: 'EPS Bus Aux',
                XDataKey: 'node_utc',
                processXDataKey: (x) => moment.unix((((x + 2400000.5) - 2440587.5) * 86400.0)).format('YYYY-MM-DDTHH:mm:ss'),
                plots: [
                  {
                    x: [],
                    y: [],
                    type: 'scatter',
                    mode: 'marker',
                    marker: {
                      color: 'orange',
                    },
                    name: 'Batt Power',
                    YDataKey: 'device_batt_power_000',
                    nodeProcess: 'neutron1:soh',
                    live: true,
                  },
                  {
                    x: [],
                    y: [],
                    type: 'scatter',
                    marker: {
                      color: 'blue',
                    },
                    name: 'Batt Charge',
                    YDataKey: 'device_batt_charge_000',
                    nodeProcess: 'neutron1:soh',
                    live: true,
                  },
                  {
                    x: [],
                    y: [],
                    type: 'scatter',
                    marker: {
                      color: 'green',
                    },
                    name: 'Batt Percentage',
                    YDataKey: 'device_batt_percentage_000',
                    nodeProcess: 'neutron1:soh',
                    live: true,
                  },
                  {
                    x: [],
                    y: [],
                    type: 'scatter',
                    marker: {
                      color: 'purple',
                    },
                    name: 'Batt Time Remaining',
                    YDataKey: 'device_batt_time_remaining_000',
                    nodeProcess: 'neutron1:soh',
                    live: true,
                  },
                ],
              },
            },
          },
          {
            i: 'satellite-neutron1-ha',
            x: 0,
            y: 4,
            w: 6,
            h: 18,
            component: {
              name: 'Chart',
              props: {
                name: 'EPS Bus Amp',
                XDataKey: 'node_utc',
                processXDataKey: (x) => moment.unix((((x + 2400000.5) - 2440587.5) * 86400.0)).format('YYYY-MM-DDTHH:mm:ss'),
                plots: [
                  {
                    x: [],
                    y: [],
                    type: 'scatter',
                    marker: {
                      color: 'red',
                    },
                    name: 'Amp 000',
                    YDataKey: 'device_bus_amp_000',
                    nodeProcess: 'neutron1:soh',
                    live: true,
                  },
                  {
                    x: [],
                    y: [],
                    type: 'scatter',
                    marker: {
                      color: 'orange',
                    },
                    name: 'Amp 001',
                    YDataKey: 'device_bus_amp_001',
                    nodeProcess: 'neutron1:soh',
                    live: true,
                  },
                  {
                    x: [],
                    y: [],
                    type: 'scatter',
                    marker: {
                      color: 'blue',
                    },
                    name: 'Amp 002',
                    YDataKey: 'device_bus_amp_002',
                    nodeProcess: 'neutron1:soh',
                    live: true,
                  },
                  {
                    x: [],
                    y: [],
                    type: 'scatter',
                    marker: {
                      color: 'gray',
                    },
                    name: '12V Amperage',
                    YDataKey: 'device_bus_amp_003',
                    nodeProcess: 'neutron1:soh',
                    live: true,
                  },
                  {
                    x: [],
                    y: [],
                    type: 'scatter',
                    marker: {
                      color: 'yellow',
                    },
                    name: 'Batt Amerage',
                    YDataKey: 'device_batt_amp_000',
                    nodeProcess: 'neutron1:soh',
                    live: true,
                  },
                  {
                    x: [],
                    y: [],
                    type: 'scatter',
                    mode: 'marker',
                    marker: {
                      color: 'red',
                    },
                    name: 'Batt Voltage',
                    YDataKey: 'device_batt_volt_000',
                    nodeProcess: 'neutron1:soh',
                    live: true,
                  },
                ],
              },
            },
          },
          {
            i: 'satellite-neutron1-hb',
            x: 6,
            y: 4,
            w: 6,
            h: 18,
            component: {
              name: 'Chart',
              props: {
                name: 'EPS Bus Volt',
                XDataKey: 'node_utc',
                processXDataKey: (x) => moment.unix((((x + 2400000.5) - 2440587.5) * 86400.0)).format('YYYY-MM-DDTHH:mm:ss'),
                plots: [
                  {
                    x: [],
                    y: [],
                    type: 'scatter',
                    marker: {
                      color: 'red',
                    },
                    name: 'Volt 000',
                    YDataKey: 'device_bus_volt_000',
                    nodeProcess: 'neutron1:soh',
                    live: true,
                  },
                  {
                    x: [],
                    y: [],
                    type: 'scatter',
                    marker: {
                      color: 'orange',
                    },
                    name: 'Volt 001',
                    YDataKey: 'device_bus_volt_001',
                    nodeProcess: 'neutron1:soh',
                    live: true,
                  },
                  {
                    x: [],
                    y: [],
                    type: 'scatter',
                    marker: {
                      color: 'blue',
                    },
                    name: 'Volt 002',
                    YDataKey: 'device_bus_volt_002',
                    nodeProcess: 'neutron1:soh',
                    live: true,
                  },
                  {
                    x: [],
                    y: [],
                    type: 'scatter',
                    marker: {
                      color: 'gray',
                    },
                    name: 'Volt 003',
                    YDataKey: 'device_bus_volt_003',
                    nodeProcess: 'neutron1:soh',
                    live: true,
                  },
                  {
                    x: [],
                    y: [],
                    type: 'scatter',
                    mode: 'marker',
                    marker: {
                      color: 'red',
                    },
                    name: 'Batt Voltage',
                    YDataKey: 'device_batt_volt_000',
                    nodeProcess: 'neutron1:soh',
                    live: true,
                  },
                ],
              },
            },
          },
          {
            i: 'satellite-default-ia',
            x: 0,
            y: 5,
            w: 6,
            h: 18,
            component: {
              name: 'Chart',
              props: {
                name: 'EPS Battery Charge Regulator Amp',
                XDataKey: 'node_utc',
                processXDataKey: (x) => moment.unix((((x + 2400000.5) - 2440587.5) * 86400.0)).format('YYYY-MM-DDTHH:mm:ss'),
                plots: [
                  {
                    x: [],
                    y: [],
                    type: 'scatter',
                    marker: {
                      color: 'blue',
                    },
                    name: 'Amp 000',
                    YDataKey: 'device_bcreg_amp_000',
                    nodeProcess: 'neutron1:soh',
                    live: true,
                  },
                  {
                    x: [],
                    y: [],
                    type: 'scatter',
                    marker: {
                      color: 'orange',
                    },
                    name: 'Amp 001',
                    YDataKey: 'device_bcreg_amp_001',
                    nodeProcess: 'neutron1:soh',
                    live: true,
                  },
                  {
                    x: [],
                    y: [],
                    type: 'scatter',
                    marker: {
                      color: 'yellow',
                    },
                    name: 'Amp 002',
                    YDataKey: 'device_bcreg_amp_002',
                    nodeProcess: 'neutron1:soh',
                    live: true,
                  },
                ],
              },
            },
          },
          {
            i: 'satellite-default-ib',
            x: 6,
            y: 5,
            w: 6,
            h: 18,
            component: {
              name: 'Chart',
              props: {
                name: 'EPS Battery Charge Regulator Volt',
                XDataKey: 'node_utc',
                processXDataKey: (x) => moment.unix((((x + 2400000.5) - 2440587.5) * 86400.0)).format('YYYY-MM-DDTHH:mm:ss'),
                plots: [
                  {
                    x: [],
                    y: [],
                    type: 'scatter',
                    marker: {
                      color: 'blue',
                    },
                    name: 'Volt 000',
                    YDataKey: 'device_bcreg_volt_000',
                    nodeProcess: 'neutron1:soh',
                    live: true,
                  },
                  {
                    x: [],
                    y: [],
                    type: 'scatter',
                    marker: {
                      color: 'orange',
                    },
                    name: 'Volt 001',
                    YDataKey: 'device_bcreg_volt_001',
                    nodeProcess: 'neutron1:soh',
                    live: true,
                  },
                  {
                    x: [],
                    y: [],
                    type: 'scatter',
                    marker: {
                      color: 'yellow',
                    },
                    name: 'Volt 002',
                    YDataKey: 'device_bcreg_volt_002',
                    nodeProcess: 'neutron1:soh',
                    live: true,
                  },
                ],
              },
            },
          },
          {
            i: 'satellite-default-ja',
            x: 0,
            y: 6,
            w: 6,
            h: 19,
            component: {
              name: 'Chart',
              props: {
                name: 'EPS PDM Switch Amp',
                XDataKey: 'node_utc',
                processXDataKey: (x) => moment.unix((((x + 2400000.5) - 2440587.5) * 86400.0)).format('YYYY-MM-DDTHH:mm:ss'),
                plots: [
                  {
                    x: [],
                    y: [],
                    type: 'scatter',
                    marker: {
                      color: 'yellow',
                    },
                    name: 'Amp 000',
                    YDataKey: 'device_swch_amp_000',
                    nodeProcess: 'neutron1:soh',
                    live: true,
                  },
                  {
                    x: [],
                    y: [],
                    type: 'scatter',
                    marker: {
                      color: 'blue',
                    },
                    name: 'Amp 001',
                    YDataKey: 'device_swch_amp_001',
                    nodeProcess: 'neutron1:soh',
                    live: true,
                  },
                  {
                    x: [],
                    y: [],
                    type: 'scatter',
                    marker: {
                      color: 'orange',
                    },
                    name: 'Amp 002',
                    YDataKey: 'device_swch_amp_002',
                    nodeProcess: 'neutron1:soh',
                    live: true,
                  },
                  {
                    x: [],
                    y: [],
                    type: 'scatter',
                    marker: {
                      color: 'green',
                    },
                    name: 'Amp 003',
                    YDataKey: 'device_swch_amp_003',
                    nodeProcess: 'neutron1:soh',
                    live: true,
                  },
                  {
                    x: [],
                    y: [],
                    type: 'scatter',
                    marker: {
                      color: 'blue',
                    },
                    name: 'Amp 004',
                    YDataKey: 'device_swch_amp_004',
                    nodeProcess: 'neutron1:soh',
                    live: true,
                  },
                  {
                    x: [],
                    y: [],
                    type: 'scatter',
                    marker: {
                      color: 'purple',
                    },
                    name: 'Amp 005',
                    YDataKey: 'device_swch_amp_005',
                    nodeProcess: 'neutron1:soh',
                    live: true,
                  },
                  {
                    x: [],
                    y: [],
                    type: 'scatter',
                    marker: {
                      color: 'red',
                    },
                    name: 'Amp 006',
                    YDataKey: 'device_swch_amp_006',
                    nodeProcess: 'neutron1:soh',
                    live: true,
                  },
                  {
                    x: [],
                    y: [],
                    type: 'scatter',
                    marker: {
                      color: 'black',
                    },
                    name: 'Amp 007',
                    YDataKey: 'device_swch_amp_007',
                    nodeProcess: 'neutron1:soh',
                    live: true,
                  },
                  {
                    x: [],
                    y: [],
                    type: 'scatter',
                    marker: {
                      color: 'pink',
                    },
                    name: 'Amp 008',
                    YDataKey: 'device_swch_amp_008',
                    nodeProcess: 'neutron1:soh',
                    live: true,
                  },
                  {
                    x: [],
                    y: [],
                    type: 'scatter',
                    marker: {
                      color: 'cyan',
                    },
                    name: 'Amp 009',
                    YDataKey: 'device_swch_amp_009',
                    nodeProcess: 'neutron1:soh',
                    live: true,
                  },

                ],
              },
            },
          },
          {
            i: 'satellite-default-jb',
            x: 6,
            y: 6,
            w: 6,
            h: 19,
            component: {
              name: 'Chart',
              props: {
                name: 'EPS PDM Switch Volt',
                XDataKey: 'node_utc',
                processXDataKey: (x) => moment.unix((((x + 2400000.5) - 2440587.5) * 86400.0)).format('YYYY-MM-DDTHH:mm:ss'),
                plots: [
                  {
                    x: [],
                    y: [],
                    type: 'scatter',
                    marker: {
                      color: 'yellow',
                    },
                    name: 'Volt 000',
                    YDataKey: 'device_swch_volt_000',
                    nodeProcess: 'neutron1:soh',
                    live: true,
                  },
                  {
                    x: [],
                    y: [],
                    type: 'scatter',
                    marker: {
                      color: 'blue',
                    },
                    name: 'Volt 001',
                    YDataKey: 'device_swch_volt_001',
                    nodeProcess: 'neutron1:soh',
                    live: true,
                  },
                  {
                    x: [],
                    y: [],
                    type: 'scatter',
                    marker: {
                      color: 'orange',
                    },
                    name: 'Volt 002',
                    YDataKey: 'device_swch_volt_002',
                    nodeProcess: 'neutron1:soh',
                    live: true,
                  },
                  {
                    x: [],
                    y: [],
                    type: 'scatter',
                    marker: {
                      color: 'green',
                    },
                    name: 'Volt 003',
                    YDataKey: 'device_swch_volt_003',
                    nodeProcess: 'neutron1:soh',
                    live: true,
                  },
                  {
                    x: [],
                    y: [],
                    type: 'scatter',
                    marker: {
                      color: 'blue',
                    },
                    name: 'Volt 004',
                    YDataKey: 'device_swch_volt_004',
                    nodeProcess: 'neutron1:soh',
                    live: true,
                  },
                  {
                    x: [],
                    y: [],
                    type: 'scatter',
                    marker: {
                      color: 'purple',
                    },
                    name: 'Volt 005',
                    YDataKey: 'device_swch_volt_005',
                    nodeProcess: 'neutron1:soh',
                    live: true,
                  },
                  {
                    x: [],
                    y: [],
                    type: 'scatter',
                    marker: {
                      color: 'red',
                    },
                    name: 'Volt 006',
                    YDataKey: 'device_swch_volt_006',
                    nodeProcess: 'neutron1:soh',
                    live: true,
                  },
                  {
                    x: [],
                    y: [],
                    type: 'scatter',
                    marker: {
                      color: 'black',
                    },
                    name: 'Volt 007',
                    YDataKey: 'device_swch_volt_007',
                    nodeProcess: 'neutron1:soh',
                    live: true,
                  },
                  {
                    x: [],
                    y: [],
                    type: 'scatter',
                    marker: {
                      color: 'pink',
                    },
                    name: 'Volt 008',
                    YDataKey: 'device_swch_volt_008',
                    nodeProcess: 'neutron1:soh',
                    live: true,
                  },
                  {
                    x: [],
                    y: [],
                    type: 'scatter',
                    marker: {
                      color: 'cyan',
                    },
                    name: 'Volt 009',
                    YDataKey: 'device_swch_volt_009',
                    nodeProcess: 'neutron1:soh',
                    live: true,
                  },
                ],
              },
            },
          },
        ],
      },
      defaultLayoutSimple: {
        lg: [
          {
            i: 'satellite-simple-neutron1-a',
            x: 0,
            y: 0,
            w: 3,
            h: 7,
            component: {
              name: 'Status',
            },
          },
          {
            i: 'satellite-simple-neutron1-ba',
            x: 3,
            y: 0,
            w: 3,
            h: 7,
            component: {
              name: 'DisplayValue',
              props: {
                name: 'beagle1 EPS',
                displayValues: [
                  {
                    name: 'Battery Capacity',
                    nodeProcess: 'beagle1:eps',
                    dataKey: 'node_battcap',
                    unit: 'Whr',
                    processDataKey: (x) => x.toFixed(2),
                  },
                  {
                    name: 'Battery Percent',
                    nodeProcess: 'beagle1:eps',
                    dataKey: 'device_batt_percentage_000',
                    unit: '%',
                    processDataKey: (x) => x.toFixed(2),
                  },
                  {
                    name: 'Power Gen',
                    nodeProcess: 'beagle1:eps',
                    dataKey: 'node_powgen',
                    unit: 'W',
                    processDataKey: (x) => x.toFixed(2),
                  },
                  {
                    name: 'Power Use',
                    nodeProcess: 'beagle1:eps',
                    dataKey: 'node_powuse',
                    unit: 'W',
                    processDataKey: (x) => x.toFixed(2),
                  },
                ],
              },
            },
          },
          {
            i: 'satellite-simple-neutron1-b',
            x: 6,
            y: 0,
            w: 3,
            h: 7,
            component: {
              name: 'DisplayValue',
              props: {
                name: 'beagle1 CPU',
                displayValues: [
                  {
                    name: 'CPU Load',
                    nodeProcess: 'beagle1:cpu',
                    dataKey: 'device_cpu_load_000',
                    unit: '',
                    processDataKey: (x) => x.toFixed(2),
                  },
                  {
                    name: 'CPU Utilization',
                    nodeProcess: 'beagle1:cpu',
                    dataKey: 'cpu_utilization_000',
                    unit: '',
                    processDataKey: (x) => x.toFixed(2),
                  },
                  {
                    name: 'Max GiB',
                    nodeProcess: 'beagle1:cpu',
                    dataKey: 'device_cpu_maxgib_000',
                    unit: 'GiB',
                    processDataKey: (x) => x.toFixed(2),
                  },
                  {
                    name: 'GiB',
                    nodeProcess: 'beagle1:cpu',
                    dataKey: 'device_cpu_gib_000',
                    unit: 'GiB',
                    processDataKey: (x) => x.toFixed(2),
                  },
                ],
              },
            },
          },
          {
            i: 'satellite-simple-neutron1-c',
            x: 9,
            y: 0,
            w: 3,
            h: 7,
            component: {
              name: 'Replacement',
            },
          },
          {
            i: 'satellite-simple-neutron1-d',
            x: 0,
            y: 1,
            w: 12,
            h: 10,
            component: {
              name: 'Commands',
            },
          },
          {
            i: 'satellite-simple-neutron1-e',
            x: 0,
            y: 2,
            w: 6,
            h: 21,
            component: {
              name: 'Globe',
              props: {
                name: 'Orbit',
                orbits: [
                  {
                    name: 'neutron1',
                    modelFileName: 'cubesat1.glb',
                    nodeProcess: 'cubesat1:propagator_simple',
                    dataKey: 'node_loc_pos_eci',
                    live: true,
                    position: [21.289373, 157.917480, 350000.0],
                    orientation: {
                      d: {
                        x: 0,
                        y: 0,
                        z: 0,
                      },
                      w: 0,
                    },
                  },
                ],
                overlays: [
                  {
                    color: 'CRIMSON',
                    geoJson: {
                      type: 'Polygon',
                      coordinates: [
                        [[30, 10], [40, 40], [20, 40], [10, 20], [30, 10]],
                      ],
                    },
                  },
                ],
              },
            },
          },
          {
            i: 'satellite-simple-neutron1-f',
            x: 6,
            y: 2,
            w: 6,
            h: 21,
            component: {
              name: 'Attitude',
              props: {
                name: 'Attitude',
                attitudes: [
                  {
                    name: 'n1',
                    nodeProcess: 'cubesat1:propagator_simple',
                    dataKey: 'node_loc_att_icrf',
                    quaternions: {
                      d: {
                        x: 0,
                        y: 0,
                        z: 0,
                      },
                      w: 0,
                    },
                    live: true,
                  },
                ],
              },
            },
          },
          {
            i: 'satellite-simple-neutron1-g',
            x: 0,
            y: 3,
            w: 12,
            h: 18,
            component: {
              name: 'Chart',
              props: {
                name: 'CPU',
                XDataKey: 'node_utc',
                processXDataKey: (x) => moment.unix((((x + 2400000.5) - 2440587.5) * 86400.0)).format('YYYY-MM-DDTHH:mm:ss'),
                plots: [
                  {
                    x: [],
                    y: [],
                    type: 'scatter',
                    marker: {
                      color: 'red',
                    },
                    name: 'Load',
                    YDataKey: 'device_cpu_load_000',
                    processYDataKey: (x) => x,
                    nodeProcess: 'beagle1:cpu',
                    live: true,
                  },
                  {
                    x: [],
                    y: [],
                    type: 'scatter',
                    marker: {
                      color: 'blue',
                    },
                    name: 'Utilization',
                    YDataKey: 'cpu_utilization_000',
                    processYDataKey: (x) => x,
                    nodeProcess: 'beagle1:cpu',
                    live: true,
                  },
                ],
              },
            },
          },
          {
            i: 'satellite-simple-neutron1-hc',
            x: 0,
            y: 4,
            w: 12,
            h: 18,
            component: {
              name: 'Chart',
              props: {
                name: 'EPS Bus Aux',
                XDataKey: 'node_utc',
                processXDataKey: (x) => moment.unix((((x + 2400000.5) - 2440587.5) * 86400.0)).format('YYYY-MM-DDTHH:mm:ss'),
                plots: [
                  {
                    x: [],
                    y: [],
                    type: 'scatter',
                    mode: 'marker',
                    marker: {
                      color: 'orange',
                    },
                    name: 'Batt Power',
                    YDataKey: 'device_batt_power_000',
                    nodeProcess: 'beagle1:eps',
                    live: true,
                  },
                  {
                    x: [],
                    y: [],
                    type: 'scatter',
                    marker: {
                      color: 'blue',
                    },
                    name: 'Batt Charge',
                    YDataKey: 'device_batt_charge_000',
                    nodeProcess: 'beagle1:eps',
                    live: true,
                  },
                  {
                    x: [],
                    y: [],
                    type: 'scatter',
                    marker: {
                      color: 'green',
                    },
                    name: 'Batt Percentage',
                    YDataKey: 'device_batt_percentage_000',
                    nodeProcess: 'beagle1:eps',
                    live: true,
                  },
                  {
                    x: [],
                    y: [],
                    type: 'scatter',
                    marker: {
                      color: 'purple',
                    },
                    name: 'Batt Time Remaining',
                    YDataKey: 'device_batt_time_remaining_000',
                    nodeProcess: 'beagle1:eps',
                    live: true,
                  },
                ],
              },
            },
          },
          {
            i: 'satellite-simple-neutron1-ha',
            x: 0,
            y: 4,
            w: 6,
            h: 18,
            component: {
              name: 'Chart',
              props: {
                name: 'EPS Bus Amp',
                XDataKey: 'node_utc',
                processXDataKey: (x) => moment.unix((((x + 2400000.5) - 2440587.5) * 86400.0)).format('YYYY-MM-DDTHH:mm:ss'),
                plots: [
                  {
                    x: [],
                    y: [],
                    type: 'scatter',
                    marker: {
                      color: 'red',
                    },
                    name: 'Amp 000',
                    YDataKey: 'device_bus_amp_000',
                    nodeProcess: 'beagle1:eps',
                    live: true,
                  },
                  {
                    x: [],
                    y: [],
                    type: 'scatter',
                    marker: {
                      color: 'orange',
                    },
                    name: 'Amp 001',
                    YDataKey: 'device_bus_amp_001',
                    nodeProcess: 'beagle1:eps',
                    live: true,
                  },
                  {
                    x: [],
                    y: [],
                    type: 'scatter',
                    marker: {
                      color: 'blue',
                    },
                    name: 'Amp 002',
                    YDataKey: 'device_bus_amp_002',
                    nodeProcess: 'beagle1:eps',
                    live: true,
                  },
                  {
                    x: [],
                    y: [],
                    type: 'scatter',
                    marker: {
                      color: 'gray',
                    },
                    name: '12V Amperage',
                    YDataKey: 'device_bus_amp_003',
                    nodeProcess: 'beagle1:eps',
                    live: true,
                  },
                  {
                    x: [],
                    y: [],
                    type: 'scatter',
                    marker: {
                      color: 'yellow',
                    },
                    name: 'Batt Amerage',
                    YDataKey: 'device_batt_amp_000',
                    nodeProcess: 'beagle1:eps',
                    live: true,
                  },
                  {
                    x: [],
                    y: [],
                    type: 'scatter',
                    mode: 'marker',
                    marker: {
                      color: 'red',
                    },
                    name: 'Batt Voltage',
                    YDataKey: 'device_batt_volt_000',
                    nodeProcess: 'beagle1:eps',
                    live: true,
                  },
                ],
              },
            },
          },
          {
            i: 'satellite-simple-neutron1-hb',
            x: 6,
            y: 4,
            w: 6,
            h: 18,
            component: {
              name: 'Chart',
              props: {
                name: 'EPS Bus Volt',
                XDataKey: 'node_utc',
                processXDataKey: (x) => moment.unix((((x + 2400000.5) - 2440587.5) * 86400.0)).format('YYYY-MM-DDTHH:mm:ss'),
                plots: [
                  {
                    x: [],
                    y: [],
                    type: 'scatter',
                    marker: {
                      color: 'red',
                    },
                    name: 'Volt 000',
                    YDataKey: 'device_bus_volt_000',
                    nodeProcess: 'beagle1:eps',
                    live: true,
                  },
                  {
                    x: [],
                    y: [],
                    type: 'scatter',
                    marker: {
                      color: 'orange',
                    },
                    name: 'Volt 001',
                    YDataKey: 'device_bus_volt_001',
                    nodeProcess: 'beagle1:eps',
                    live: true,
                  },
                  {
                    x: [],
                    y: [],
                    type: 'scatter',
                    marker: {
                      color: 'blue',
                    },
                    name: 'Volt 002',
                    YDataKey: 'device_bus_volt_002',
                    nodeProcess: 'beagle1:eps',
                    live: true,
                  },
                  {
                    x: [],
                    y: [],
                    type: 'scatter',
                    marker: {
                      color: 'gray',
                    },
                    name: 'Volt 003',
                    YDataKey: 'device_bus_volt_003',
                    nodeProcess: 'beagle1:eps',
                    live: true,
                  },
                  {
                    x: [],
                    y: [],
                    type: 'scatter',
                    mode: 'marker',
                    marker: {
                      color: 'red',
                    },
                    name: 'Batt Voltage',
                    YDataKey: 'device_batt_volt_000',
                    nodeProcess: 'beagle1:eps',
                    live: true,
                  },
                ],
              },
            },
          },
          {
            i: 'satellite-simple-default-ia',
            x: 0,
            y: 5,
            w: 6,
            h: 18,
            component: {
              name: 'Chart',
              props: {
                name: 'EPS Battery Charge Regulator Amp',
                XDataKey: 'node_utc',
                processXDataKey: (x) => moment.unix((((x + 2400000.5) - 2440587.5) * 86400.0)).format('YYYY-MM-DDTHH:mm:ss'),
                plots: [
                  {
                    x: [],
                    y: [],
                    type: 'scatter',
                    marker: {
                      color: 'blue',
                    },
                    name: 'Amp 000',
                    YDataKey: 'device_bcreg_amp_000',
                    nodeProcess: 'beagle1:eps',
                    live: true,
                  },
                  {
                    x: [],
                    y: [],
                    type: 'scatter',
                    marker: {
                      color: 'orange',
                    },
                    name: 'Amp 001',
                    YDataKey: 'device_bcreg_amp_001',
                    nodeProcess: 'beagle1:eps',
                    live: true,
                  },
                  {
                    x: [],
                    y: [],
                    type: 'scatter',
                    marker: {
                      color: 'yellow',
                    },
                    name: 'Amp 002',
                    YDataKey: 'device_bcreg_amp_002',
                    nodeProcess: 'beagle1:eps',
                    live: true,
                  },
                ],
              },
            },
          },
          {
            i: 'satellite-simple-default-ib',
            x: 6,
            y: 5,
            w: 6,
            h: 18,
            component: {
              name: 'Chart',
              props: {
                name: 'EPS Battery Charge Regulator Volt',
                XDataKey: 'node_utc',
                processXDataKey: (x) => moment.unix((((x + 2400000.5) - 2440587.5) * 86400.0)).format('YYYY-MM-DDTHH:mm:ss'),
                plots: [
                  {
                    x: [],
                    y: [],
                    type: 'scatter',
                    marker: {
                      color: 'blue',
                    },
                    name: 'Volt 000',
                    YDataKey: 'device_bcreg_volt_000',
                    nodeProcess: 'beagle1:eps',
                    live: true,
                  },
                  {
                    x: [],
                    y: [],
                    type: 'scatter',
                    marker: {
                      color: 'orange',
                    },
                    name: 'Volt 001',
                    YDataKey: 'device_bcreg_volt_001',
                    nodeProcess: 'beagle1:eps',
                    live: true,
                  },
                  {
                    x: [],
                    y: [],
                    type: 'scatter',
                    marker: {
                      color: 'yellow',
                    },
                    name: 'Volt 002',
                    YDataKey: 'device_bcreg_volt_002',
                    nodeProcess: 'beagle1:eps',
                    live: true,
                  },
                ],
              },
            },
          },
          {
            i: 'satellite-simple-default-ja',
            x: 0,
            y: 6,
            w: 6,
            h: 19,
            component: {
              name: 'Chart',
              props: {
                name: 'EPS PDM Switch Amp',
                XDataKey: 'node_utc',
                processXDataKey: (x) => moment.unix((((x + 2400000.5) - 2440587.5) * 86400.0)).format('YYYY-MM-DDTHH:mm:ss'),
                plots: [
                  {
                    x: [],
                    y: [],
                    type: 'scatter',
                    marker: {
                      color: 'yellow',
                    },
                    name: 'Amp 000',
                    YDataKey: 'device_swch_amp_000',
                    nodeProcess: 'beagle1:eps',
                    live: true,
                  },
                  {
                    x: [],
                    y: [],
                    type: 'scatter',
                    marker: {
                      color: 'blue',
                    },
                    name: 'Amp 001',
                    YDataKey: 'device_swch_amp_001',
                    nodeProcess: 'beagle1:eps',
                    live: true,
                  },
                  {
                    x: [],
                    y: [],
                    type: 'scatter',
                    marker: {
                      color: 'orange',
                    },
                    name: 'Amp 002',
                    YDataKey: 'device_swch_amp_002',
                    nodeProcess: 'beagle1:eps',
                    live: true,
                  },
                  {
                    x: [],
                    y: [],
                    type: 'scatter',
                    marker: {
                      color: 'green',
                    },
                    name: 'Amp 003',
                    YDataKey: 'device_swch_amp_003',
                    nodeProcess: 'beagle1:eps',
                    live: true,
                  },
                  {
                    x: [],
                    y: [],
                    type: 'scatter',
                    marker: {
                      color: 'blue',
                    },
                    name: 'Amp 004',
                    YDataKey: 'device_swch_amp_004',
                    nodeProcess: 'beagle1:eps',
                    live: true,
                  },
                  {
                    x: [],
                    y: [],
                    type: 'scatter',
                    marker: {
                      color: 'purple',
                    },
                    name: 'Amp 005',
                    YDataKey: 'device_swch_amp_005',
                    nodeProcess: 'beagle1:eps',
                    live: true,
                  },
                  {
                    x: [],
                    y: [],
                    type: 'scatter',
                    marker: {
                      color: 'red',
                    },
                    name: 'Amp 006',
                    YDataKey: 'device_swch_amp_006',
                    nodeProcess: 'beagle1:eps',
                    live: true,
                  },
                  {
                    x: [],
                    y: [],
                    type: 'scatter',
                    marker: {
                      color: 'black',
                    },
                    name: 'Amp 007',
                    YDataKey: 'device_swch_amp_007',
                    nodeProcess: 'beagle1:eps',
                    live: true,
                  },
                  {
                    x: [],
                    y: [],
                    type: 'scatter',
                    marker: {
                      color: 'pink',
                    },
                    name: 'Amp 008',
                    YDataKey: 'device_swch_amp_008',
                    nodeProcess: 'beagle1:eps',
                    live: true,
                  },
                  {
                    x: [],
                    y: [],
                    type: 'scatter',
                    marker: {
                      color: 'cyan',
                    },
                    name: 'Amp 009',
                    YDataKey: 'device_swch_amp_009',
                    nodeProcess: 'beagle1:eps',
                    live: true,
                  },

                ],
              },
            },
          },
          {
            i: 'satellite-simple-default-jb',
            x: 6,
            y: 6,
            w: 6,
            h: 19,
            component: {
              name: 'Chart',
              props: {
                name: 'EPS PDM Switch Volt',
                XDataKey: 'node_utc',
                processXDataKey: (x) => moment.unix((((x + 2400000.5) - 2440587.5) * 86400.0)).format('YYYY-MM-DDTHH:mm:ss'),
                plots: [
                  {
                    x: [],
                    y: [],
                    type: 'scatter',
                    marker: {
                      color: 'yellow',
                    },
                    name: 'Volt 000',
                    YDataKey: 'device_swch_volt_000',
                    nodeProcess: 'beagle1:eps',
                    live: true,
                  },
                  {
                    x: [],
                    y: [],
                    type: 'scatter',
                    marker: {
                      color: 'blue',
                    },
                    name: 'Volt 001',
                    YDataKey: 'device_swch_volt_001',
                    nodeProcess: 'beagle1:eps',
                    live: true,
                  },
                  {
                    x: [],
                    y: [],
                    type: 'scatter',
                    marker: {
                      color: 'orange',
                    },
                    name: 'Volt 002',
                    YDataKey: 'device_swch_volt_002',
                    nodeProcess: 'beagle1:eps',
                    live: true,
                  },
                  {
                    x: [],
                    y: [],
                    type: 'scatter',
                    marker: {
                      color: 'green',
                    },
                    name: 'Volt 003',
                    YDataKey: 'device_swch_volt_003',
                    nodeProcess: 'beagle1:eps',
                    live: true,
                  },
                  {
                    x: [],
                    y: [],
                    type: 'scatter',
                    marker: {
                      color: 'blue',
                    },
                    name: 'Volt 004',
                    YDataKey: 'device_swch_volt_004',
                    nodeProcess: 'beagle1:eps',
                    live: true,
                  },
                  {
                    x: [],
                    y: [],
                    type: 'scatter',
                    marker: {
                      color: 'purple',
                    },
                    name: 'Volt 005',
                    YDataKey: 'device_swch_volt_005',
                    nodeProcess: 'beagle1:eps',
                    live: true,
                  },
                  {
                    x: [],
                    y: [],
                    type: 'scatter',
                    marker: {
                      color: 'red',
                    },
                    name: 'Volt 006',
                    YDataKey: 'device_swch_volt_006',
                    nodeProcess: 'beagle1:eps',
                    live: true,
                  },
                  {
                    x: [],
                    y: [],
                    type: 'scatter',
                    marker: {
                      color: 'black',
                    },
                    name: 'Volt 007',
                    YDataKey: 'device_swch_volt_007',
                    nodeProcess: 'beagle1:eps',
                    live: true,
                  },
                  {
                    x: [],
                    y: [],
                    type: 'scatter',
                    marker: {
                      color: 'pink',
                    },
                    name: 'Volt 008',
                    YDataKey: 'device_swch_volt_008',
                    nodeProcess: 'beagle1:eps',
                    live: true,
                  },
                  {
                    x: [],
                    y: [],
                    type: 'scatter',
                    marker: {
                      color: 'cyan',
                    },
                    name: 'Volt 009',
                    YDataKey: 'device_swch_volt_009',
                    nodeProcess: 'beagle1:eps',
                    live: true,
                  },
                ],
              },
            },
          },
        ],
      },
    },
    {
      name: 'hyti',
      path: '/hyti',
      icon: 'camera',
      defaultLayout: {
        lg: [
          {
            i: 'satellite-hyti-a',
            x: 0,
            y: 0,
            w: 4,
            h: 7,
            component: {
              name: 'Status',
            },
          },
          {
            i: 'satellite-hyti-bb',
            x: 4,
            y: 0,
            w: 4,
            h: 7,
            component: {
              name: 'DisplayValue',
              props: {
                name: 'Unibap CPU',
                displayValues: [
                  {
                    name: 'CPU Load',
                    nodeProcess: 'beagle1:cpu',
                    dataKey: 'device_cpu_load_000',
                    unit: '%',
                    processDataKey: (x) => x.toFixed(2),
                  },
                  {
                    name: 'GiB',
                    nodeProcess: 'beagle1:cpu',
                    dataKey: 'device_cpu_gib_000',
                    unit: 'GiB',
                    processDataKey: (x) => x.toFixed(2),
                  },
                  {
                    name: 'Max GiB',
                    nodeProcess: 'beagle1:cpu',
                    dataKey: 'device_cpu_maxgib_000',
                    unit: 'GiB',
                    processDataKey: (x) => x.toFixed(2),
                  },
                ],
              },
            },
          },
          {
            i: 'satellite-hyti-c',
            x: 8,
            y: 0,
            w: 4,
            h: 7,
            component: {
              name: 'Clock',
            },
          },
          {
            i: 'satellite-hyti-d',
            x: 0,
            y: 1,
            w: 12,
            h: 10,
            component: {
              name: 'Commands',
            },
          },
          {
            i: 'satellite-hyti-e',
            x: 0,
            y: 2,
            w: 6,
            h: 21,
            component: {
              name: 'Globe',
              props: {
                name: 'Orbit',
                orbits: [
                  {
                    name: 'neutron1',
                    modelFileName: 'cubesat1.glb',
                    nodeProcess: 'cubesat1:propagator_simple',
                    dataKey: 'node_loc_pos_eci',
                    live: true,
                    position: [21.289373, 157.917480, 350000.0],
                    orientation: {
                      d: {
                        x: 0,
                        y: 0,
                        z: 0,
                      },
                      w: 0,
                    },
                  },
                ],
              },
            },
          },
          {
            i: 'satellite-hyti-f',
            x: 6,
            y: 2,
            w: 6,
            h: 21,
            component: {
              name: 'Attitude',
              props: {
                attitudes: [
                  {
                    name: 'n1',
                    nodeProcess: 'cubesat1:propagator_simple',
                    dataKey: 'node_loc_att_icrf',
                    quaternions: {
                      d: {
                        x: 0,
                        y: 0,
                        z: 0,
                      },
                      w: 0,
                    },
                    live: true,
                  },
                ],
              },
            },
          },
          {
            i: 'satellite-hyti-g',
            x: 0,
            y: 3,
            w: 12,
            h: 18,
            component: {
              name: 'Chart',
              props: {
                name: 'Temperature',
                XDataKey: 'node_utc',
                processXDataKey: (x) => moment.unix((((x + 2400000.5) - 2440587.5) * 86400.0)).format('YYYY-MM-DDTHH:mm:ss'),
                plots: [
                  {
                    x: [],
                    y: [],
                    type: 'scatter',
                    marker: {
                      color: 'red',
                    },
                    name: '1',
                    YDataKey: 'device_tsen_temp_001',
                    processYDataKey: (x) => x - 273.15,
                    nodeProcess: 'beagle1:eps',
                    live: true,
                  },
                  {
                    x: [],
                    y: [],
                    type: 'scatter',
                    marker: {
                      color: 'blue',
                    },
                    name: '2',
                    YDataKey: 'device_tsen_temp_002',
                    processYDataKey: (x) => x - 273.15,
                    nodeProcess: 'beagle1:eps',
                    live: true,
                  },
                  {
                    x: [],
                    y: [],
                    type: 'scatter',
                    marker: {
                      color: 'orange',
                    },
                    name: '3',
                    YDataKey: 'device_tsen_temp_003',
                    processYDataKey: (x) => x - 273.15,
                    nodeProcess: 'beagle1:eps',
                    live: true,
                  },
                ],
              },
            },
          },
          {
            i: 'satellite-hyti-h',
            x: 0,
            y: 4,
            w: 12,
            h: 18,
            component: {
              name: 'Chart',
              props: {
                name: 'Voltage',
                XDataKey: 'node_utc',
                processXDataKey: (x) => moment.unix((((x + 2400000.5) - 2440587.5) * 86400.0)).format('YYYY-MM-DDTHH:mm:ss'),
                plots: [
                  {
                    x: [],
                    y: [],
                    type: 'scatter',
                    marker: {
                      color: 'red',
                    },
                    name: '5V',
                    YDataKey: 'device_bus_volt_001',
                    nodeProcess: 'beagle1:eps',
                    live: true,
                  },
                  {
                    x: [],
                    y: [],
                    type: 'scatter',
                    marker: {
                      color: 'blue',
                    },
                    name: '3.3V',
                    YDataKey: 'device_bus_volt_002',
                    nodeProcess: 'beagle1:eps',
                    live: true,
                  },
                  {
                    x: [],
                    y: [],
                    type: 'scatter',
                    marker: {
                      color: 'orange',
                    },
                    name: 'Battery Voltage',
                    YDataKey: 'device_bus_volt_003',
                    nodeProcess: 'beagle1:eps',
                    live: true,
                  },
                ],
              },
            },
          },
          {
            i: 'satellite-hyti-i',
            x: 0,
            y: 5,
            w: 12,
            h: 18,
            component: {
              name: 'Chart',
              props: {
                name: 'Amperage',
                XDataKey: 'node_utc',
                processXDataKey: (x) => moment.unix((((x + 2400000.5) - 2440587.5) * 86400.0)).format('YYYY-MM-DDTHH:mm:ss'),
                plots: [
                  {
                    x: [],
                    y: [],
                    type: 'scatter',
                    marker: {
                      color: 'red',
                    },
                    name: '5V',
                    YDataKey: 'device_bus_amp_001',
                    nodeProcess: 'beagle1:eps',
                    live: true,
                  },
                  {
                    x: [],
                    y: [],
                    type: 'scatter',
                    marker: {
                      color: 'blue',
                    },
                    name: '3.3V',
                    YDataKey: 'device_bus_amp_002',
                    nodeProcess: 'beagle1:eps',
                    live: true,
                  },
                  {
                    x: [],
                    y: [],
                    type: 'scatter',
                    marker: {
                      color: 'orange',
                    },
                    name: 'Battery Voltage',
                    YDataKey: 'device_bus_amp_003',
                    nodeProcess: 'beagle1:eps',
                    live: true,
                  },
                ],
              },
            },
          },
          {
            i: 'satellite-hyti-j',
            x: 0,
            y: 6,
            w: 12,
            h: 18,
            component: {
              name: 'Chart',
              props: {
                name: 'Battery Health',
                plots: [
                  {
                    x: [],
                    y: [],
                    type: 'scatter',
                    marker: {
                      color: 'red',
                    },
                    name: 'Battery Percentage',
                    YDataKey: 'device_batt_percentage_000',
                    nodeProcess: 'neutron1:eps',
                    live: true,
                  },
                  {
                    x: [],
                    y: [],
                    type: 'scatter',
                    mode: 'marker',
                    marker: {
                      color: 'blue',
                    },
                    name: 'Charge',
                    YDataKey: 'device_batt_charge_000',
                    nodeProcess: 'neutron1:eps',
                    live: true,
                  },
                ],
              },
            },
          },
        ],
      },
    },
  ],
};
