import { mjdToString } from '../../utility/time';

export default {
  name: 'neutron1',
  path: '/neutron1',
  icon: 'qrcode',
  defaultLayout: {
    lg: [
      {
        i: 'satellite-simple-neutron1-aaa',
        x: 0,
        y: 0,
        w: 3,
        h: 7,
        component: {
          name: 'MissionEventsDisplay',
          props: {
            nodes: ['neutron1', 'beagle1'],
          },
        },
      },
      {
        i: 'satellite-simple-neutron1-a',
        x: 0,
        y: 0,
        w: 3,
        h: 7,
        component: {
          name: 'Status',
        },
      },
      {
        i: 'satellite-simple-neutron1-ba',
        x: 3,
        y: 0,
        w: 3,
        h: 7,
        component: {
          name: 'DisplayValue',
          props: {
            name: 'beagle1 EPS',
            displayValues: [
              {
                name: 'Battery Capacity',
                nodeProcess: 'beagle1:eps',
                dataKey: 'node_battcap',
                timeDataKey: 'node_utc',
                unit: 'Whr',
                processDataKey: (x) => x.toFixed(2),
              },
              {
                name: 'Battery Percent',
                nodeProcess: 'beagle1:eps',
                dataKey: 'device_batt_percentage_000',
                timeDataKey: 'node_utc',
                unit: '%',
                processDataKey: (x) => x.toFixed(4),
              },
              {
                name: 'Power Gen',
                nodeProcess: 'beagle1:eps',
                timeDataKey: 'node_utc',
                dataKey: 'node_powgen',
                unit: 'W',
                processDataKey: (x) => x.toFixed(2),
              },
              {
                name: 'Power Use',
                nodeProcess: 'beagle1:eps',
                timeDataKey: 'node_utc',
                dataKey: 'node_powuse',
                unit: 'W',
                processDataKey: (x) => x.toFixed(2),
              },
            ],
          },
        },
      },
      {
        i: 'satellite-simple-neutron1-b',
        x: 6,
        y: 0,
        w: 3,
        h: 7,
        component: {
          name: 'DisplayValue',
          props: {
            name: 'CPU',
            displayValues: [
              {
                name: 'beagle1 CPU Load',
                nodeProcess: 'beagle1:cpu',
                dataKey: 'device_cpu_load_000',
                timeDataKey: 'device_cpu_utc_000',
                unit: '',
                processDataKey: (x) => x.toFixed(2),
              },
              {
                name: 'OBC CPU Load',
                nodeProcess: 'neutron1:cpu',
                dataKey: 'device_cpu_load_000',
                timeDataKey: 'device_cpu_utc_001',
                unit: '',
                processDataKey: (x) => x.toFixed(2),
              },
            ],
          },
        },
      },
      {
        i: 'satellite-simple-neutron1-c',
        x: 9,
        y: 0,
        w: 3,
        h: 7,
        component: {
          name: 'DisplayValue',
          props: {
            name: 'Temperature',
            displayValues: [
              {
                name: 'Battery Temp',
                nodeProcess: 'beagle1:eps',
                dataKey: 'device_batt_temp_000',
                timeDataKey: 'device_batt_utc_000',
                unit: 'C',
                processDataKey: (x) => (x - 272.15).toFixed(2),
              },
              {
                name: 'Batt Daughterboard 1 Temp',
                nodeProcess: 'beagle1:eps',
                dataKey: 'device_tsen_temp_000',
                timeDataKey: 'device_tsen_utc_000',
                unit: 'C',
                processDataKey: (x) => (x - 272.15).toFixed(2),
              },
              {
                name: 'Batt Daughterboard 2 Temp',
                nodeProcess: 'beagle1:eps',
                dataKey: 'device_tsen_temp_001',
                timeDataKey: 'device_tsen_utc_001',
                unit: 'C',
                processDataKey: (x) => (x - 272.15).toFixed(2),
              },
              {
                name: 'Batt Daughterboard 2 Temp',
                nodeProcess: 'beagle1:eps',
                dataKey: 'device_tsen_temp_002',
                timeDataKey: 'device_tsen_utc_002',
                unit: 'C',
                processDataKey: (x) => (x - 272.15).toFixed(2),
              },
              {
                name: 'Batt Daughterboard 2 Temp',
                nodeProcess: 'beagle1:eps',
                dataKey: 'device_tsen_temp_003',
                timeDataKey: 'device_tsen_utc_003',
                unit: 'C',
                processDataKey: (x) => (x - 272.15).toFixed(2),
              },
              {
                name: 'BBB CPU Temp',
                nodeProcess: 'beagle1:cpu',
                dataKey: 'device_cpu_temp_000',
                timeDataKey: 'device_cpu_utc_000',
                unit: 'C',
                processDataKey: (x) => (x - 272.15).toFixed(2),
              },
              {
                name: 'EPS DU CPU Temp',
                nodeProcess: 'beagle1:eps',
                dataKey: 'device_cpu_temp_001',
                timeDataKey: 'device_cpu_utc_001',
                unit: 'C',
                processDataKey: (x) => (x - 272.15).toFixed(2),
              },
              {
                name: 'CubeComputer CPU Temp',
                nodeProcess: 'beagle1:eps',
                dataKey: 'device_cpu_temp_002',
                timeDataKey: 'device_cpu_utc_002',
                unit: 'C',
                processDataKey: (x) => (x - 272.15).toFixed(2),
              },
              {
                name: 'IMU Temp',
                nodeProcess: 'beagle1:adcs',
                dataKey: 'device_imu_temp_000',
                timeDataKey: 'device_imu_utc_000',
                unit: 'C',
                processDataKey: (x) => (x - 272.15).toFixed(2),
              },
              {
                name: 'Battery Temp',
                nodeProcess: 'beagle1:eps',
                dataKey: 'device_batt_temp_000',
                timeDataKey: 'device_batt_utc_000',
                unit: 'K',
                processDataKey: (x) => x.toFixed(2),
              },
              {
                name: 'Batt Daughterboard 1 Temp',
                nodeProcess: 'beagle1:eps',
                dataKey: 'device_tsen_temp_000',
                unit: 'K',
                processDataKey: (x) => x.toFixed(2),
              },
              {
                name: 'Batt Daughterboard 2 Temp',
                nodeProcess: 'beagle1:eps',
                dataKey: 'device_tsen_temp_001',
                unit: 'K',
                processDataKey: (x) => x.toFixed(2),
              },
              {
                name: 'Batt Daughterboard 2 Temp',
                nodeProcess: 'beagle1:eps',
                dataKey: 'device_tsen_temp_002',
                unit: 'K',
                processDataKey: (x) => x.toFixed(2),
              },
              {
                name: 'Batt Daughterboard 2 Temp',
                nodeProcess: 'beagle1:eps',
                dataKey: 'device_tsen_temp_003',
                unit: 'K',
                processDataKey: (x) => x.toFixed(2),
              },
              {
                name: 'BBB CPU Temp',
                nodeProcess: 'beagle1:cpu',
                dataKey: 'device_cpu_temp_000',
                unit: 'K',
                processDataKey: (x) => x.toFixed(2),
              },
              {
                name: 'EPS DU CPU Temp',
                nodeProcess: 'beagle1:eps',
                dataKey: 'device_cpu_temp_001',
                unit: 'K',
                processDataKey: (x) => x.toFixed(2),
              },
              {
                name: 'CubeComputer CPU Temp',
                nodeProcess: 'beagle1:adcs',
                dataKey: 'device_cpu_temp_002',
                unit: 'K',
                processDataKey: (x) => x.toFixed(2),
              },
              {
                name: 'IMU Temp',
                nodeProcess: 'beagle1:adcs',
                dataKey: 'device_imu_temp_000',
                unit: 'K',
                processDataKey: (x) => x.toFixed(2),
              },
            ],
          },
        },
      },
      {
        i: 'satellite-simple-neutron1-f',
        x: 6,
        y: 8,
        w: 6,
        h: 21,
        component: {
          name: 'Attitude',
          props: {
            name: 'Attitude',
            attitudes: [
              {
                name: 'n1',
                nodeProcess: 'cubesat1:propagator_simple',
                dataKey: 'node_loc_att_icrf',
                quaternions: {
                  d: {
                    x: 0,
                    y: 0,
                    z: 0,
                  },
                  w: 0,
                },
                live: true,
              },
            ],
          },
        },
      },
      {
        i: 'satellite-simple-neutron1-g',
        x: 0,
        y: 3,
        w: 6,
        h: 18,
        component: {
          name: 'Chart',
          props: {
            name: 'CPU',
            XDataKey: 'node_utc',
            processXDataKey: (x) => mjdToString(x),
            plots: [
              {
                x: [],
                y: [],
                type: 'scatter',
                marker: {
                  color: 'red',
                },
                name: 'beagle1 Load',
                YDataKey: 'device_cpu_load_000',
                processYDataKey: (x) => x,
                nodeProcess: 'beagle1:cpu',
                live: true,
              },
              {
                x: [],
                y: [],
                type: 'scatter',
                marker: {
                  color: 'blue',
                },
                name: 'OBC Load',
                YDataKey: 'device_cpu_load_000',
                processYDataKey: (x) => x,
                nodeProcess: 'neutron1:cpu',
                live: true,
              },
            ],
          },
        },
      },
      {
        i: 'satellite-simple-default-iaa',
        x: 6,
        y: 3,
        w: 6,
        h: 18,
        component: {
          name: 'Chart',
          props: {
            name: 'Thermal',
            XDataKey: 'node_utc',
            processXDataKey: (x) => mjdToString(x),
            plots: [
              {
                x: [],
                y: [],
                type: 'scatter',
                marker: {
                  color: 'blue',
                },
                name: 'Battery Motherboard Temperature',
                YDataKey: 'device_batt_temp_000',
                processYDataKey: (x) => x,
                nodeProcess: 'beagle1:eps',
                live: true,
              },
              {
                x: [],
                y: [],
                type: 'scatter',
                marker: {
                  color: 'blue',
                },
                name: 'Battery Daughterboard Temperature 1',
                YDataKey: 'device_tsen_temp_000',
                processYDataKey: (x) => x,
                nodeProcess: 'beagle1:eps',
                live: true,
              },
              {
                x: [],
                y: [],
                type: 'scatter',
                marker: {
                  color: 'orange',
                },
                name: 'Battery Daughterboard 2 Temperature',
                YDataKey: 'device_tsen_temp_001',
                processYDataKey: (x) => x,
                nodeProcess: 'beagle1:eps',
                live: true,
              },
              {
                x: [],
                y: [],
                type: 'scatter',
                marker: {
                  color: 'red',
                },
                name: 'Battery Daughterboard 2 Temperature',
                YDataKey: 'device_tsen_temp_002',
                processYDataKey: (x) => x,
                nodeProcess: 'beagle1:eps',
                live: true,
              },
              {
                x: [],
                y: [],
                type: 'scatter',
                marker: {
                  color: 'yellow',
                },
                name: 'Battery Daughterboard 2 Temperature',
                YDataKey: 'device_tsen_temp_003',
                processYDataKey: (x) => x,
                nodeProcess: 'beagle1:eps',
                live: true,
              },
              {
                x: [],
                y: [],
                type: 'scatter',
                marker: {
                  color: 'yellow',
                },
                name: 'BBB Temperature',
                YDataKey: 'device_cpu_temp_000',
                processYDataKey: (x) => x,
                nodeProcess: 'beagle1:cpu',
                live: true,
              },
              {
                x: [],
                y: [],
                type: 'scatter',
                marker: {
                  color: 'green',
                },
                name: 'EPS DU Temperature',
                YDataKey: 'device_cpu_temp_001',
                processYDataKey: (x) => x,
                nodeProcess: 'beagle1:eps',
                live: true,
              },
              {
                x: [],
                y: [],
                type: 'scatter',
                marker: {
                  color: 'green',
                },
                name: 'CubeComputer Temperature',
                YDataKey: 'device_cpu_temp_002',
                processYDataKey: (x) => x,
                nodeProcess: 'beagle1:adcs',
                live: true,
              },
              {
                x: [],
                y: [],
                type: 'scatter',
                marker: {
                  color: 'violet',
                },
                name: 'IMU Temperature',
                YDataKey: 'device_imu_temp_000',
                processYDataKey: (x) => x,
                nodeProcess: 'beagle1:adcs',
                live: true,
              },
            ],
          },
        },
      },
      {
        i: 'satellite-simple-neutron1-hc',
        x: 0,
        y: 4,
        w: 6,
        h: 18,
        component: {
          name: 'Chart',
          props: {
            name: 'EPS Bus Aux',
            XDataKey: 'node_utc',
            processXDataKey: (x) => mjdToString(x),
            plots: [
              {
                x: [],
                y: [],
                type: 'scatter',
                mode: 'marker',
                marker: {
                  color: 'orange',
                },
                name: 'Batt Power',
                YDataKey: 'device_batt_power_000',
                processYDataKey: (x) => x,
                nodeProcess: 'beagle1:eps',
                live: true,
              },
              {
                x: [],
                y: [],
                type: 'scatter',
                marker: {
                  color: 'blue',
                },
                name: 'Batt Charge',
                YDataKey: 'device_batt_charge_000',
                processYDataKey: (x) => x,
                nodeProcess: 'beagle1:eps',
                live: true,
              },
              {
                x: [],
                y: [],
                type: 'scatter',
                marker: {
                  color: 'green',
                },
                name: 'Batt Percentage',
                YDataKey: 'device_batt_percentage_000',
                processYDataKey: (x) => x,
                nodeProcess: 'beagle1:eps',
                live: true,
              },
              {
                x: [],
                y: [],
                type: 'scatter',
                marker: {
                  color: 'purple',
                },
                name: 'Batt Time Remaining',
                YDataKey: 'device_batt_time_remaining_000',
                processYDataKey: (x) => x,
                nodeProcess: 'beagle1:eps',
                live: true,
              },
            ],
          },
        },
      },
      {
        i: 'satellite-simple-neutron1-ha',
        x: 6,
        y: 4,
        w: 6,
        h: 18,
        component: {
          name: 'Chart',
          props: {
            name: 'EPS Bus Power',
            XDataKey: 'node_utc',
            processXDataKey: (x) => mjdToString(x),
            plots: [
              {
                x: [],
                y: [],
                type: 'scatter',
                marker: {
                  color: 'red',
                },
                name: 'Power 000',
                YDataKey: 'device_bus_power_000',
                processYDataKey: (x) => x,
                nodeProcess: 'beagle1:eps',
                live: true,
              },
              {
                x: [],
                y: [],
                type: 'scatter',
                marker: {
                  color: 'orange',
                },
                name: 'Power 001',
                YDataKey: 'device_bus_power_001',
                processYDataKey: (x) => x,
                nodeProcess: 'beagle1:eps',
                live: true,
              },
              {
                x: [],
                y: [],
                type: 'scatter',
                marker: {
                  color: 'blue',
                },
                name: 'Power 002',
                YDataKey: 'device_bus_power_002',
                processYDataKey: (x) => x,
                nodeProcess: 'beagle1:eps',
                live: true,
              },
              {
                x: [],
                y: [],
                type: 'scatter',
                marker: {
                  color: 'gray',
                },
                name: 'Power 003',
                YDataKey: 'device_bus_power_003',
                processYDataKey: (x) => x,
                nodeProcess: 'beagle1:eps',
                live: true,
              },
            ],
          },
        },
      },
      {
        i: 'satellite-simple-default-ia',
        x: 0,
        y: 5,
        w: 6,
        h: 18,
        component: {
          name: 'Chart',
          props: {
            name: 'EPS Battery Charge Regulator Power',
            XDataKey: 'node_utc',
            processXDataKey: (x) => mjdToString(x),
            plots: [
              {
                x: [],
                y: [],
                type: 'scatter',
                marker: {
                  color: 'blue',
                },
                name: 'Power 000',
                YDataKey: 'device_bcreg_power_000',
                processYDataKey: (x) => x,
                nodeProcess: 'beagle1:eps',
                live: true,
              },
              {
                x: [],
                y: [],
                type: 'scatter',
                marker: {
                  color: 'orange',
                },
                name: 'Power 001',
                YDataKey: 'device_bcreg_power_001',
                processYDataKey: (x) => x,
                nodeProcess: 'beagle1:eps',
                live: true,
              },
              {
                x: [],
                y: [],
                type: 'scatter',
                marker: {
                  color: 'yellow',
                },
                name: 'Power 002',
                YDataKey: 'device_bcreg_power_002',
                processYDataKey: (x) => x,
                nodeProcess: 'beagle1:eps',
                live: true,
              },
            ],
          },
        },
      },
      {
        i: 'satellite-simple-default-ja',
        x: 6,
        y: 5,
        w: 6,
        h: 18,
        component: {
          name: 'Chart',
          props: {
            name: 'EPS PDM Switch Power',
            XDataKey: 'node_utc',
            processXDataKey: (x) => mjdToString(x),
            plots: [
              {
                x: [],
                y: [],
                type: 'scatter',
                marker: {
                  color: 'yellow',
                },
                name: 'BBB Power',
                YDataKey: 'bbb_power',
                processYDataKey: (x) => x,
                nodeProcess: 'beagle1:eps',
                live: true,
              },
              {
                x: [],
                y: [],
                type: 'scatter',
                marker: {
                  color: 'blue',
                },
                name: 'OBC Power',
                YDataKey: 'obc_power',
                processYDataKey: (x) => x,
                nodeProcess: 'beagle1:eps',
                live: true,
              },
              {
                x: [],
                y: [],
                type: 'scatter',
                marker: {
                  color: 'orange',
                },
                name: 'Duplex Power',
                YDataKey: 'duplex_power',
                processYDataKey: (x) => x,
                nodeProcess: 'beagle1:eps',
                live: true,
              },
              {
                x: [],
                y: [],
                type: 'scatter',
                marker: {
                  color: 'green',
                },
                name: 'TRXVU Power',
                YDataKey: 'trxvu_power',
                processYDataKey: (x) => x,
                nodeProcess: 'beagle1:eps',
                live: true,
              },
              {
                x: [],
                y: [],
                type: 'scatter',
                marker: {
                  color: 'green',
                },
                name: 'ASU Power',
                YDataKey: 'asu_power',
                processYDataKey: (x) => x,
                nodeProcess: 'beagle1:eps',
                live: true,
              },
            ],
          },
        },
      },
      {
        i: 'satellite-simple-default-jb',
        x: 0,
        y: 7,
        w: 12,
        h: 18,
        component: {
          name: 'Chart',
          props: {
            name: 'EPS Power',
            XDataKey: 'node_utc',
            processXDataKey: (x) => mjdToString(x),
            plots: [
              {
                x: [],
                y: [],
                type: 'scatter',
                marker: {
                  color: 'green',
                },
                name: 'Power Generation',
                YDataKey: 'node_powgen',
                processYDataKey: (x) => x,
                nodeProcess: 'beagle1:eps',
                live: true,
              },
              {
                x: [],
                y: [],
                type: 'scatter',
                marker: {
                  color: 'blue',
                },
                name: 'Power Usage',
                YDataKey: 'node_powuse',
                processYDataKey: (x) => x,
                nodeProcess: 'beagle1:eps',
                live: true,
              },
            ],
          },
        },
      },
      {
        i: 'satellite-simple-neutron1-d',
        x: 0,
        y: 8,
        w: 12,
        h: 10,
        component: {
          name: 'Commands',
          props: {
            commands: [
              {
                name: 'mov_agent_cpu',
                command: 'neutron1 exec add_value mov_agent_cpu',
              },
            ],
          },
        },
      },
      {
        i: 'satellite-simple-neutron1-e',
        x: 0,
        y: 9,
        w: 6,
        h: 21,
        component: {
          name: 'Globe',
          props: {
            name: 'Orbit',
            orbits: [
              {
                name: 'neutron1',
                modelFileName: 'cubesat1.glb',
                nodeProcess: 'cubesat1:propagator_simple',
                dataKey: 'node_loc_pos_eci',
                timeDataKey: 'node_utc',
                live: true,
                position: [21.289373, 157.917480, 350000.0],
                orientation: {
                  d: {
                    x: 0,
                    y: 0,
                    z: 0,
                  },
                  w: 0,
                },
              },
            ],
            overlays: [
              {
                color: 'CRIMSON',
                geoJson: {
                  type: 'Polygon',
                  coordinates: [
                    [[30, 10], [40, 40], [20, 40], [10, 20], [30, 10]],
                  ],
                },
              },
            ],
          },
        },
      },
    ],
  },
  tabs: {
    BBB: {
      lg: [

      ],
    },
    'ISIS Radio': {
      lg: [

      ],
    },
    'Duplex Radio': {
      lg: [

      ],
    },
    Battery: {
      lg: [

      ],
    },
    Payload: {
      lg: [

      ],
    },
    EPS: {
      lg: [
        {
          i: 'satellite-neutron1-tab-eps-a',
          x: 0,
          y: 0,
          w: 3,
          h: 7,
          component: {
            name: 'Status',
          },
        },
        {
          i: 'satellite-neutron1-tab-eps-ba',
          x: 3,
          y: 0,
          w: 3,
          h: 7,
          component: {
            name: 'DisplayValue',
            props: {
              name: 'EPS Overview',
              displayValues: [
                {
                  name: 'Battery Capacity',
                  nodeProcess: 'beagle1:eps',
                  dataKey: 'node_battcap',
                  timeDataKey: 'node_utc',
                  unit: 'Whr',
                  processDataKey: (x) => x.toFixed(2),
                },
                {
                  name: 'Battery Percent',
                  nodeProcess: 'beagle1:eps',
                  dataKey: 'device_batt_percentage_000',
                  timeDataKey: 'node_utc',
                  unit: '%',
                  processDataKey: (x) => x.toFixed(4),
                },
                {
                  name: 'Power Gen',
                  nodeProcess: 'beagle1:eps',
                  timeDataKey: 'node_utc',
                  dataKey: 'node_powgen',
                  unit: 'W',
                  processDataKey: (x) => x.toFixed(2),
                },
                {
                  name: 'Power Use',
                  nodeProcess: 'beagle1:eps',
                  timeDataKey: 'node_utc',
                  dataKey: 'node_powuse',
                  unit: 'W',
                  processDataKey: (x) => x.toFixed(2),
                },
                {
                  name: 'Battery Temperature',
                  nodeProcess: 'beagle1:eps',
                  dataKey: 'device_batt_temp_000',
                  timeDataKey: 'node_utc',
                  unit: 'C',
                  processDataKey: (x) => (x - 272.15).toFixed(2),
                },
              ],
            },
          },
        },
        {
          i: 'satellite-neutron1-tab-eps-ha',
          x: 0,
          y: 4,
          w: 6,
          h: 18,
          component: {
            name: 'Chart',
            props: {
              name: 'EPS Bus Amp',
              XDataKey: 'node_utc',
              processXDataKey: (x) => mjdToString(x),
              plots: [
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  marker: {
                    color: 'red',
                  },
                  name: 'Amp 000',
                  YDataKey: 'device_bus_amp_000',
                  processYDataKey: (x) => x,
                  nodeProcess: 'beagle1:eps',
                  live: true,
                },
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  marker: {
                    color: 'orange',
                  },
                  name: 'Amp 001',
                  YDataKey: 'device_bus_amp_001',
                  processYDataKey: (x) => x,
                  nodeProcess: 'beagle1:eps',
                  live: true,
                },
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  marker: {
                    color: 'blue',
                  },
                  name: 'Amp 002',
                  YDataKey: 'device_bus_amp_002',
                  processYDataKey: (x) => x,
                  nodeProcess: 'beagle1:eps',
                  live: true,
                },
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  marker: {
                    color: 'gray',
                  },
                  name: '12V Amperage',
                  YDataKey: 'device_bus_amp_003',
                  processYDataKey: (x) => x,
                  nodeProcess: 'beagle1:eps',
                  live: true,
                },
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  marker: {
                    color: 'yellow',
                  },
                  name: 'Batt Amerage',
                  YDataKey: 'device_batt_amp_000',
                  processYDataKey: (x) => x,
                  nodeProcess: 'beagle1:eps',
                  live: true,
                },
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  mode: 'marker',
                  marker: {
                    color: 'red',
                  },
                  name: 'Batt Voltage',
                  YDataKey: 'device_batt_volt_000',
                  processYDataKey: (x) => x,
                  nodeProcess: 'beagle1:eps',
                  live: true,
                },
              ],
            },
          },
        },
        {
          i: 'satellite-neutron1-tab-eps-hb',
          x: 6,
          y: 4,
          w: 6,
          h: 18,
          component: {
            name: 'Chart',
            props: {
              name: 'EPS Bus Volt',
              XDataKey: 'node_utc',
              processXDataKey: (x) => mjdToString(x),
              plots: [
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  marker: {
                    color: 'red',
                  },
                  name: 'Volt 000',
                  YDataKey: 'device_bus_volt_000',
                  processYDataKey: (x) => x,
                  nodeProcess: 'beagle1:eps',
                  live: true,
                },
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  marker: {
                    color: 'orange',
                  },
                  name: 'Volt 001',
                  YDataKey: 'device_bus_volt_001',
                  processYDataKey: (x) => x,
                  nodeProcess: 'beagle1:eps',
                  live: true,
                },
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  marker: {
                    color: 'blue',
                  },
                  name: 'Volt 002',
                  YDataKey: 'device_bus_volt_002',
                  processYDataKey: (x) => x,
                  nodeProcess: 'beagle1:eps',
                  live: true,
                },
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  marker: {
                    color: 'gray',
                  },
                  name: 'Volt 003',
                  YDataKey: 'device_bus_volt_003',
                  processYDataKey: (x) => x,
                  nodeProcess: 'beagle1:eps',
                  live: true,
                },
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  mode: 'marker',
                  marker: {
                    color: 'red',
                  },
                  name: 'Batt Voltage',
                  YDataKey: 'device_batt_volt_000',
                  processYDataKey: (x) => x,
                  nodeProcess: 'beagle1:eps',
                  live: true,
                },
              ],
            },
          },
        },
        {
          i: 'satellite-neutron1-tab-eps-ia',
          x: 0,
          y: 5,
          w: 6,
          h: 18,
          component: {
            name: 'Chart',
            props: {
              name: 'EPS Battery Charge Regulator Amp',
              XDataKey: 'node_utc',
              processXDataKey: (x) => mjdToString(x),
              plots: [
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  marker: {
                    color: 'blue',
                  },
                  name: 'Amp 000',
                  YDataKey: 'device_bcreg_amp_000',
                  processYDataKey: (x) => x,
                  nodeProcess: 'beagle1:eps',
                  live: true,
                },
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  marker: {
                    color: 'orange',
                  },
                  name: 'Amp 001',
                  YDataKey: 'device_bcreg_amp_001',
                  processYDataKey: (x) => x,
                  nodeProcess: 'beagle1:eps',
                  live: true,
                },
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  marker: {
                    color: 'yellow',
                  },
                  name: 'Amp 002',
                  YDataKey: 'device_bcreg_amp_002',
                  processYDataKey: (x) => x,
                  nodeProcess: 'beagle1:eps',
                  live: true,
                },
              ],
            },
          },
        },
        {
          i: 'satellite-neutron1-tab-eps-ib',
          x: 6,
          y: 5,
          w: 6,
          h: 18,
          component: {
            name: 'Chart',
            props: {
              name: 'EPS Battery Charge Regulator Volt',
              XDataKey: 'node_utc',
              processXDataKey: (x) => mjdToString(x),
              plots: [
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  marker: {
                    color: 'blue',
                  },
                  name: 'Volt 000',
                  YDataKey: 'device_bcreg_volt_000',
                  processYDataKey: (x) => x,
                  nodeProcess: 'beagle1:eps',
                  live: true,
                },
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  marker: {
                    color: 'orange',
                  },
                  name: 'Volt 001',
                  YDataKey: 'device_bcreg_volt_001',
                  processYDataKey: (x) => x,
                  nodeProcess: 'beagle1:eps',
                  live: true,
                },
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  marker: {
                    color: 'yellow',
                  },
                  name: 'Volt 002',
                  YDataKey: 'device_bcreg_volt_002',
                  processYDataKey: (x) => x,
                  nodeProcess: 'beagle1:eps',
                  live: true,
                },
              ],
            },
          },
        },
        {
          i: 'satellite-neutron1-tab-eps-ja',
          x: 0,
          y: 6,
          w: 6,
          h: 19,
          component: {
            name: 'Chart',
            props: {
              name: 'EPS PDM Switch Amp',
              XDataKey: 'node_utc',
              processXDataKey: (x) => mjdToString(x),
              plots: [
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  marker: {
                    color: 'yellow',
                  },
                  name: 'Amp 000',
                  YDataKey: 'device_swch_amp_000',
                  processYDataKey: (x) => x,
                  nodeProcess: 'beagle1:eps',
                  live: true,
                },
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  marker: {
                    color: 'blue',
                  },
                  name: 'Amp 001',
                  YDataKey: 'device_swch_amp_001',
                  processYDataKey: (x) => x,
                  nodeProcess: 'beagle1:eps',
                  live: true,
                },
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  marker: {
                    color: 'orange',
                  },
                  name: 'Amp 002',
                  YDataKey: 'device_swch_amp_002',
                  processYDataKey: (x) => x,
                  nodeProcess: 'beagle1:eps',
                  live: true,
                },
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  marker: {
                    color: 'green',
                  },
                  name: 'Amp 003',
                  YDataKey: 'device_swch_amp_003',
                  processYDataKey: (x) => x,
                  nodeProcess: 'beagle1:eps',
                  live: true,
                },
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  marker: {
                    color: 'blue',
                  },
                  name: 'Amp 004',
                  YDataKey: 'device_swch_amp_004',
                  processYDataKey: (x) => x,
                  nodeProcess: 'beagle1:eps',
                  live: true,
                },
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  marker: {
                    color: 'purple',
                  },
                  name: 'Amp 005',
                  YDataKey: 'device_swch_amp_005',
                  processYDataKey: (x) => x,
                  nodeProcess: 'beagle1:eps',
                  live: true,
                },
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  marker: {
                    color: 'red',
                  },
                  name: 'Amp 006',
                  YDataKey: 'device_swch_amp_006',
                  processYDataKey: (x) => x,
                  nodeProcess: 'beagle1:eps',
                  live: true,
                },
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  marker: {
                    color: 'black',
                  },
                  name: 'Amp 007',
                  YDataKey: 'device_swch_amp_007',
                  processYDataKey: (x) => x,
                  nodeProcess: 'beagle1:eps',
                  live: true,
                },
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  marker: {
                    color: 'pink',
                  },
                  name: 'Amp 008',
                  YDataKey: 'device_swch_amp_008',
                  processYDataKey: (x) => x,
                  nodeProcess: 'beagle1:eps',
                  live: true,
                },
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  marker: {
                    color: 'cyan',
                  },
                  name: 'Amp 009',
                  YDataKey: 'device_swch_amp_009',
                  processYDataKey: (x) => x,
                  nodeProcess: 'beagle1:eps',
                  live: true,
                },
              ],
            },
          },
        },
        {
          i: 'satellite-neutron1-tab-eps-jb',
          x: 6,
          y: 6,
          w: 6,
          h: 19,
          component: {
            name: 'Chart',
            props: {
              name: 'EPS PDM Switch Volt',
              XDataKey: 'node_utc',
              processXDataKey: (x) => mjdToString(x),
              plots: [
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  marker: {
                    color: 'yellow',
                  },
                  name: 'Volt 000',
                  YDataKey: 'device_swch_volt_000',
                  processYDataKey: (x) => x,
                  nodeProcess: 'beagle1:eps',
                  live: true,
                },
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  marker: {
                    color: 'blue',
                  },
                  name: 'Volt 001',
                  YDataKey: 'device_swch_volt_001',
                  processYDataKey: (x) => x,
                  nodeProcess: 'beagle1:eps',
                  live: true,
                },
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  marker: {
                    color: 'orange',
                  },
                  name: 'Volt 002',
                  YDataKey: 'device_swch_volt_002',
                  processYDataKey: (x) => x,
                  nodeProcess: 'beagle1:eps',
                  live: true,
                },
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  marker: {
                    color: 'green',
                  },
                  name: 'Volt 003',
                  YDataKey: 'device_swch_volt_003',
                  processYDataKey: (x) => x,
                  nodeProcess: 'beagle1:eps',
                  live: true,
                },
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  marker: {
                    color: 'blue',
                  },
                  name: 'Volt 004',
                  YDataKey: 'device_swch_volt_004',
                  processYDataKey: (x) => x,
                  nodeProcess: 'beagle1:eps',
                  live: true,
                },
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  marker: {
                    color: 'purple',
                  },
                  name: 'Volt 005',
                  YDataKey: 'device_swch_volt_005',
                  processYDataKey: (x) => x,
                  nodeProcess: 'beagle1:eps',
                  live: true,
                },
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  marker: {
                    color: 'red',
                  },
                  name: 'Volt 006',
                  YDataKey: 'device_swch_volt_006',
                  processYDataKey: (x) => x,
                  nodeProcess: 'beagle1:eps',
                  live: true,
                },
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  marker: {
                    color: 'black',
                  },
                  name: 'Volt 007',
                  YDataKey: 'device_swch_volt_007',
                  processYDataKey: (x) => x,
                  nodeProcess: 'beagle1:eps',
                  live: true,
                },
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  marker: {
                    color: 'pink',
                  },
                  name: 'Volt 008',
                  YDataKey: 'device_swch_volt_008',
                  processYDataKey: (x) => x,
                  nodeProcess: 'beagle1:eps',
                  live: true,
                },
                {
                  x: [],
                  y: [],
                  type: 'scatter',
                  marker: {
                    color: 'cyan',
                  },
                  name: 'Volt 009',
                  YDataKey: 'device_swch_volt_009',
                  processYDataKey: (x) => x,
                  nodeProcess: 'beagle1:eps',
                  live: true,
                },
              ],
            },
          },
        },
      ],
    },
    OBC: {
      lg: [
        {
          i: 'satellite-neutron1-tab-obc-a',
          x: 0,
          y: 0,
          w: 3,
          h: 7,
          component: {
            name: 'Status',
          },
        },
        {
          i: 'satellite-neutron1-tab-obc-ba',
          x: 3,
          y: 0,
          w: 3,
          h: 7,
          component: {
            name: 'DisplayValue',
            props: {
              name: 'EPS Overview',
              displayValues: [
                {
                  name: 'Battery Capacity',
                  nodeProcess: 'beagle1:eps',
                  dataKey: 'node_battcap',
                  timeDataKey: 'node_utc',
                  unit: 'Whr',
                  processDataKey: (x) => x.toFixed(2),
                },
                {
                  name: 'Battery Percent',
                  nodeProcess: 'beagle1:eps',
                  dataKey: 'device_batt_percentage_000',
                  timeDataKey: 'node_utc',
                  unit: '%',
                  processDataKey: (x) => x.toFixed(4),
                },
                {
                  name: 'Power Gen',
                  nodeProcess: 'beagle1:eps',
                  timeDataKey: 'node_utc',
                  dataKey: 'node_powgen',
                  unit: 'W',
                  processDataKey: (x) => x.toFixed(2),
                },
                {
                  name: 'Power Use',
                  nodeProcess: 'beagle1:eps',
                  timeDataKey: 'node_utc',
                  dataKey: 'node_powuse',
                  unit: 'W',
                  processDataKey: (x) => x.toFixed(2),
                },
                {
                  name: 'Battery Temperature',
                  nodeProcess: 'beagle1:eps',
                  dataKey: 'device_batt_temp_000',
                  timeDataKey: 'node_utc',
                  unit: 'C',
                  processDataKey: (x) => (x - 272.15).toFixed(2),
                },
              ],
            },
          },
        },
      ],
    },
    ADCS: {
      lg: [
        {
          i: 'satellite-neutron1-tab-adcs-a',
          x: 0,
          y: 0,
          w: 3,
          h: 7,
          component: {
            name: 'Status',
          },
        },
      ],
    },
  },
};
